### PR TITLE
Active font color is now visible in both color grids

### LINKED ISSUE #51: The active font color is only selected in the document colors
This seems wrong to me. Because you will never see the checkmark in the normal grid. It will always be in the document colors.

image

### LINKED ISSUE #2299: The active font color is only selected in the document colors
This seems wrong to me. Because you will never see the checkmark in the normal grid. It will always be in the document colors.

image

### PR DESCRIPTION
**Pull request by msamsel**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Active font color is now visible in both color grids. Closes ckeditor/ckeditor5#2299.

---

### Additional information

* Required PR: ckeditor/ckeditor5-ui#522
* I add some improvements in unit test names to fit them more to `should` convention.

### CODE REVIEW

File: tests/ui/colortableview.js [hunk 1]
```diff
@@ -469,17 +469,40 @@ describe( 'ColorTableView', () => {
...
 			const redStaticColorTile = staticColorsGrid.items.find( tile => tile.color === '#00FF00' );
-			const redDocumentColorTile = documentColorsGrid.items.get( 0 );
+			const activeDocumentColorTile = documentColorsGrid.items.find( tile => tile.isOn );
 
 			expect( redStaticColorTile.isOn ).to.be.true;
-			expect( redDocumentColorTile.isOn ).to.be.false;
+			expect( activeDocumentColorTile ).to.be.undefined;
+		} );
+
+		it( 'should not have selction for unknow colors exceeding document colors limit', () => {
```
Comment (oleq) [inline tests/ui/colortableview.js]:
```suggestion
		it( 'should not have a selection for unknown colors exceeding document colors limit', () => {
```

**Review by oleq — CHANGES_REQUESTED** [review]
Found this bug:

**Comment by msamsel** [comment]
@oleq source of this bug is in the ckeditor5-ui, because ColorGridView does not set up `isOn` value for newly added tiles. I add a PR for that: https://github.com/ckeditor/ckeditor5-ui/pull/522.
