### PR TITLE
Lazy loading for the font color/bg dropdowns

### LINKED ISSUE #6192: Font color/background UI rendering should be improved
## 📝 Provide detailed reproduction steps (if any)

We should improve rendering time for both foreground and background color dropdowns.

For instance in case of loading editor with short content it took ~126ms and 100ms respectively. That time combined took **28%** of entire editor initialization time (editor with small and simple content 220ms was 1.23ms).

Profiler flame chart

### ✔️ Expected result

Faster 🏃‍♀️

### ❌ Actual result

Slow 🐢

## 📃 Other details

This is a follow-up of #5880.

* Browser: Chrome
* OS: Windows (should be cross system)
* CKEditor version: latest `master`

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

### PR DESCRIPTION
**Pull request by mlewand**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Other: Implemented lazy loading for the font color and background dropdown. This will reduce editor initialization time. Closes ckeditor/ckeditor5#6192.

---

### Additional information

It's difficult to easily pull this optimization for the font color / bg plugin.

First of all this plugin [stores its model in the view](https://ckeditor.com/docs/ckeditor5/16.0.0/api/module_font_ui_colortableview-ColorTableView.html#member-documentColors) - so you need the view to have things running.

There's no clear UI and business logic separation for this plugin. For example, `ColorGridView` class (so type that we'd like to defer) [holds a selected color](https://github.com/ckeditor/ckeditor5-font/blob/c65579arc/colorgrid/colorgridview.js#L48).

It works, and the tests are passing - but the solution is not super pretty.

### CODE REVIEW

File: src/ui/colortableview.js [hunk 1]
```diff
@@ -118,19 +118,21 @@ export default class ColorTableView extends View {
 		 * Preserves the reference to {@link module:ui/colorgrid/colorgrid~ColorGridView} used to create
 		 * the default (static) color set.
 		 *
+		 * The property is loaded once the the parent dropdown is opened the first time.
+		 *
 		 * @readonly
-		 * @member {module:ui/colorgrid/colorgrid~ColorGridView}
+		 * @member {module:ui/colorgrid/colorgrid~ColorGridView/undefined}
```
Comment (Reinmar) [inline src/ui/colortableview.js]: `|undefined`

File: src/ui/colortableview.js [hunk 2]
```diff
@@ -252,6 +240,38 @@ export default class ColorTableView extends View {
 		this.keystrokes.listenTo( this.element );
 	}
 
+	/**
+	 * Renders and appends {@link #staticColorsGrid} and {@link #documentColorsGrid} views.
```
Comment (Reinmar) [inline src/ui/colortableview.js]: SRP – render or append. Or change the name at least.

**Comment by Reinmar** [comment]
For me, the solution looks completely fine. I'm not saying that the surrounding code is good and I didn't even look at it. But this change itself is very similar to what we did in other plugins, so that sounds fine.

**Review by Reinmar — CHANGES_REQUESTED** [review]
As commented.

File: src/ui/colortableview.js (hunk 2 above)
Comment (mlewand) [reply src/ui/colortableview.js]: The thing here is that in order to append it it also has to render it first (and this is the most intense operation, which we want to avoid). I'll turn it into append then.

**Comment by Reinmar** [comment]
Next goal – getting rid of this layout and style recalculations :) Fonts work fine now.

image
